# Generated by Django 5.0.14 on 2025-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="body",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
